const assert = require('assert'); const fs=require('fs'); const vm=require('vm'); const path=require('path');
const source=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const expression=name=>{const start=source.indexOf(`const ${name} =`);assert(start>=0,`missing ${name}`);const end=source.indexOf('\n        };',start);assert(end>start);return source.slice(start,end+11)};
const context={};vm.createContext(context);
for(const name of ['extractStorageCapacity','normalizeStorageHeaderResult','reconcileStorageEvidence','formatStorageReview']) vm.runInContext(`${expression(name)}\nthis.${name}=${name};`,context);
for(const [input,expected] of [['161/400','400'],['391 / 875','875'],['１，２３４／５，６７８','5678'],['400',''],['(15)',''],['9/12','12'],['寶可夢 161/400','']]) assert.strictEqual(context.extractStorageCapacity(input),expected);
const norm=v=>JSON.parse(JSON.stringify(context.normalizeStorageHeaderResult(v)));
let n=norm({header_type:'pokemon',relevant_header_label:'寶可夢',storage_text:'161/400',outcome:'verified'});
assert.strictEqual(n.poke_bag,'400');assert.strictEqual(n.raw_pair,'161/400');assert.strictEqual(n.status,'verified');
n=norm({header_type:'item',relevant_header_label:'道具',storage_text:'391/875',outcome:'verified'});assert.strictEqual(n.item_bag,'875');
n=norm({header_type:'none',relevant_header_label:'蛋',storage_text:'',outcome:'not_visible'});assert.strictEqual(n.status,'not_visible');assert.strictEqual(n.poke_bag,'');
for(const bad of [{header_type:'pokemon',relevant_header_label:'寶可夢',storage_text:'400',outcome:'verified'},{header_type:'pokemon',relevant_header_label:'蛋',storage_text:'9/12',outcome:'verified'}]) assert.strictEqual(norm(bad).structurally_complete,false);
const candidate=(value,index=1)=>({image_index:index,poke_bag_candidate:{value,raw_pair:`1/${value}`,image_index:index},verification_status:'not_visible',verification:null});
let d=context.reconcileStorageEvidence([candidate('400')],'poke_bag');assert.strictEqual(d.status,'pending');assert.strictEqual(d.accepted_value,'');assert.strictEqual(d.candidates[0].raw_pair,'1/400');
d=context.reconcileStorageEvidence([{...candidate('400'),verification_status:'request_failed'}],'poke_bag');assert.deepStrictEqual([...d.verification_statuses],['request_failed']);
const verified=(value,index)=>({image_index:index,poke_bag_candidate:null,verification_status:'verified',verification:{field:'poke_bag',value,raw_pair:`1/${value}`,image_index:index}});
d=context.reconcileStorageEvidence([candidate('400'),verified('400',2)],'poke_bag');assert.strictEqual(d.status,'verified');assert.strictEqual(d.accepted_value,'400');
for(const records of [[candidate('400'),verified('500',2)],[verified('500',2),candidate('400')]]){d=context.reconcileStorageEvidence(records,'poke_bag');assert.strictEqual(d.status,'conflicting');assert.strictEqual(d.accepted_value,'');}
assert(context.formatStorageReview('poke_bag',context.reconcileStorageEvidence([candidate('400')],'poke_bag')).includes('待確認'));
assert(source.includes('「蛋」的數對一律不是寶可夢或道具容量'));
assert.strictEqual((source.slice(source.indexOf('const verifyStorageHeader = async'),source.indexOf('const requestSingleImageClassification = async')).match(/requestStorageHeaderVerification\(/g)||[]).length,2);
assert(source.includes("const DEDICATED_VERIFICATION_FIELDS = new Set(['poke_bag', 'item_bag'])"));
assert(source.includes("canvas.toDataURL('image/png')"));
console.log('Storage capacity recognition and reconciliation tests passed; 0 live OpenAI requests.');
